name: raktr
services:
  backend:
    image: ghcr.io/mboldi/raktr/backend:main
    depends_on:
      db:
        condition: service_healthy
    environment:
      SENTRY_DSN: ""
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/raktrdb
    ports:
      - "127.0.0.1:8080:8080"
  frontend:
    image: ghcr.io/mboldi/raktr/frontend:main
    depends_on:
      - backend
    ports:
      - "127.0.0.1:80:8080"
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raktrdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  pgdata:
