TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE comments CASCADE;
TRUNCATE TABLE container_devices CASCADE;
TRUNCATE TABLE locations CASCADE;
TRUNCATE TABLE owners CASCADE;
TRUNCATE TABLE scannables CASCADE;
TRUNCATE TABLE users CASCADE;
