CREATE TABLE owners (
      id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      name TEXT UNIQUE NOT NULL,
      in_sch_inventory BOOLEAN NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
      created_by UUID NOT NULL,
      updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
      updated_by UUID NOT NULL
);
