TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE comments CASCADE;
TRUNCATE TABLE container_devices CASCADE;
TRUNCATE TABLE locations CASCADE;
TRUNCATE TABLE owners CASCADE;
TRUNCATE TABLE scannables CASCADE;
TRUNCATE TABLE users CASCADE;

DELETE FROM configs;
INSERT INTO configs (key, value, data_type) VALUES
    ('RENT_TEAM_NAME', '', 'STRING'),
    ('RENT_TEAM_LEADER_NAME', '', 'STRING'),
    ('RENT_FIRST_SIGNER_NAME', '', 'STRING'),
    ('RENT_FIRST_SIGNER_TITLE', '', 'STRING'),
    ('RENT_SECOND_SIGNER_NAME', '', 'STRING'),
    ('RENT_SECOND_SIGNER_TITLE', '', 'STRING'),
    ('FORCE_EAN8', 'false', 'BOOLEAN');
