TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE comments CASCADE;
TRUNCATE TABLE container_devices CASCADE;
TRUNCATE TABLE locations CASCADE;
TRUNCATE TABLE owners CASCADE;
TRUNCATE TABLE scannables CASCADE;
TRUNCATE TABLE users CASCADE;

DELETE FROM configs;
INSERT INTO configs (key, value) VALUES
    ('RENT_TEAM_NAME', ''),
    ('RENT_TEAM_LEADER_NAME', ''),
    ('RENT_FIRST_SIGNER_NAME', ''),
    ('RENT_FIRST_SIGNER_TITLE', ''),
    ('RENT_SECOND_SIGNER_NAME', ''),
    ('RENT_SECOND_SIGNER_TITLE', ''),
    ('FORCE_EAN8', 'false');
